Seccion47Admin/Seccion.Web/Models/ViewModels/ExpensesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Seccion.Web.Models.ViewModels
{
	public class ExpensesViewModel
	{
        public int TbFuneralExpensesId { get; set; }
        [Display(Name = "Empleado Solicitante")]
        public int TbEmployeeId { get; set; }
        [Display(Name = "No Prestamo")]
        public string OrderNumberGF { get; set; }
        [Display(Name = "Fecha de Creación")]
        public string DateCreate { get; set; }
        [Display(Name = "Concepto Servicio")]
        public string ServiceConcept { get; set; }
        [Display(Name = "Tipo de Pago")]
        public string PaymentType { get; set; }
        [Display(Name = "Clave Voucher")]
        public string VoucherKey { get; set; }
        [Display(Name = "Descontar a:")]
        public string AvalName { get; set; }
        [Display(Name = "Total a Pagar")]
        public decimal PaymentAmount { get; set; }
        [Display(Name = "Periodo de Pagos")]
        public string PeriodsPayment { get; set; }
        [Display(Name = "Abono Catorcenal/Mensual")]
        public decimal AbonoCatorcenalMensual { get; set; }
        [Display(Name = "Observaciones:")]
        [DataType(DataType.MultilineText)]
        public string Comments { get; set; }
    }
}

Seccion47Admin/Seccion.Web/Controllers/CommonController.cs
using Seccion.Service.ServiceInterface;
using Seccion.Web.Models.GridListModel;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Seccion.Web.Controllers
{
    public class CommonController : Controller
    {
		private readonly IEmployeeService employeeService;

		public CommonController(IEmployeeService employeeService)
		{
			this.employeeService = employeeService;
		}
        // GET: Common
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult DataTableMenu(MenuIdModel model)
        {
            return PartialView("_TableMenu", model);
        }
        [HttpGet]
        public async Task<JsonResult> GetEmployeeAval()
        {
            var listEmployee = await employeeService.GetEmployeeData();


            return Json(listEmployee, JsonRequestBehavior.AllowGet);
        }
    }
}

Seccion47Admin/Seccion.Web/Controllers/ExpensesController.cs
using AutoMapper;
using Seccion.Model.Models;
using Seccion.Service.Common.Message;
using Seccion.Service.ServiceInterface;
using Seccion.Web.Common;
using Seccion.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Seccion.Web.Controllers
{
    [Authorize]
    public class ExpensesController : Controller
    {
		private readonly INotifier notifier;
		private readonly IEmployeeService employeeService;

		public ExpensesController(INotifier notifier, IEmployeeService employeeService)
		{
			this.notifier = notifier;
			this.employeeService = employeeService;
		}
        // GET: Expenses
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> CreateExpenses()
        {
            var listEmployee = await employeeService.GetEmployeeAllForRequest();
            ViewBag.Employee = new SelectList(listEmployee.OrderBy(x => x.TbEmployeeId), "TbEmployeeId", "EmployeeNameComplet");
            ViewBag.PaymentType = ListsDrops.PaymentType();
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> CreateExpenses(ExpensesViewModel model)
        {
			try
			{
                var expenses = Mapper.Map<ExpensesViewModel, TbFuneralExpenses>(model);
                expenses.DateCreate = DateTime.Now;
                expenses.DateInsert = DateTime.Now;
                expenses.UserInsert = User.Identity.Name;
            }
			catch (Exception ex)
			{
                return View("Error", new HandleErrorInfo(ex, "ListExpenses", "Expenses"));
            }
            return View();
        }
    }
}

Seccion47Admin/Seccion.Web/Views/Expenses/CreateExpenses.cshtml
@model Seccion.Web.Models.ViewModels.ExpensesViewModel
@{
	ViewBag.Title = "CreateExpenses";
	Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<div class="row">
	<div class="col-12">
		@*<form id="formRegisterUser" class="form-horizontal" method="post" action="/AccountUser/RegisterUser" role="form" novalidate="novalidate" autocomplete="off">*@
		@using (Html.BeginForm("RegisterUser", "AccountUser", FormMethod.Post, new { id = "formExpenses", role = "form", autocomplete = "off" }))
		{
			@Html.AntiForgeryToken()
			<div class="h-100 bg-white pt-0 radius-1 shadow-lg mx-auto">
				<div class="border-t-3 w-100 brc-dark radius-t-1"></div>
				<div class="card border-0 h-100" id="card-8">
					<div class="card-header  brc-dark-l2">
						<h5 class="card-title text-110 text-dark font-bold pt-1 text-uppercase">
							<i class="fa fa-table mr-2px" aria-hidden="true"></i>
							Registro de Gasto Funerario
						</h5>
					</div><!-- /.card-header -->

					<div class="card-body bg-white p-0 collapse show">
						<br />

						<div class="p-3">

							<div class="row">
								<div class="col-md-6">

									<div id="divEmpleado" class="form-group">
										@Html.LabelFor(model => model.TbEmployeeId, htmlAttributes: new { @class = "font-bolder" })
										@Html.DropDownListFor(model => model.TbEmployeeId, (IEnumerable<SelectListItem>)ViewBag.Employee, "", htmlAttributes: new { @class = "form-control chosen border-l-4", @data_placeholder = "Seleccionar", required = "required" })
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.ServiceConcept, htmlAttributes: new { @class = "font-bolder" })
										@Html.EditorFor(model => model.ServiceConcept, new { htmlAttributes = new { @class = "form-control", required = "required" } })
									</div>
									<div id="divTipoPago" class="form-group">
										@Html.LabelFor(model => model.PaymentType, htmlAttributes: new { @class = "font-bolder" })
										@Html.DropDownList("PaymentType", null, "", htmlAttributes: new { @class = "form-control chosen", required = "required", @data_placeholder = "Seleccionar" })
									</div>
									<div id="divClaveBaucher" class="form-group">
										@Html.LabelFor(model => model.VoucherKey, htmlAttributes: new { @class = "font-bolder" })
										@Html.EditorFor(model => model.VoucherKey, new { htmlAttributes = new { @class = "form-control" } })
									</div>
									<div id="divComprobanter" class="form-group">
										<label class="font-bolder">Comprobante Baucher(Opcional):</label>
										<input type="file" id="fileBaucher" name="fileBaucher">
									</div>
									<div id="divPersonaDescontar" class="form-group">
										@Html.LabelFor(model => model.AvalName, htmlAttributes: new { @class = "font-bolder" })
										<select multiple="" class="form-control chosen" name="AvalName" id="AvalName" data-placeholder="Selecionar">
										</select>

									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "font-bolder" })
										<input class="form-control text-left" id="PaymentAmount" name="PaymentAmount" required="required" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'digits': 2, 'digitsOptional': false, 'prefix': '$ ', 'placeholder': '0'" inputmode="numeric">

									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.PeriodsPayment, htmlAttributes: new { @class = "font-bolder" })
										<input class="form-control" id="PeriodsPayment" name="PeriodsPayment" required="required" data-inputmask="'mask': '9', 'repeat': 10, 'greedy' : false" />
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.PeriodsPayment, htmlAttributes: new { @class = "font-bolder" })
										<input class="form-control" id="PeriodsPayment" name="PeriodsPayment" required="required" data-inputmask="'mask': '9', 'repeat': 10, 'greedy' : false" />
									</div>
									<div class="form-group">
										@Html.LabelFor(model => model.AbonoCatorcenalMensual, htmlAttributes: new { @class = "font-bolder" })
										<input class="form-control" id="AbonoCatorcenalMensual" name="AbonoCatorcenalMensual" readonly data-inputmask="'mask': '9', 'repeat': 10, 'greedy' : false" />
									</div>
									<div class="form-group">
										<label class="font-bolder"></label>
										<button id="btnCalcular" type="button" class="btn btn-md btn-app btn-danger btn-block  radius-1 border-b-2 pl-2px py-2px btn-bold text-uppercase text-center">
											<span class="bgc-white-tp9 shadow-sm radius-2px px-25 mr-25 ">
												<i class="fa fa-calculator text-white-tp2 text-110 mt-3px" aria-hidden="true"></i>
											</span>
											realizar calculo
										</button>
									</div>
								</div>

							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										@Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "font-bolder" })
										@Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control", maxlength = "400" } })
									</div>
								</div>
							</div>

						</div>



						<div class="bgc-light px-3 py-2 border-t-2 brc-dark-l2 d-flex ">
							<a href="@Url.Action("ListAccountUsers","AccountUser")" class="btn btn-dark radius-1 border-b-2 d-inline-flex align-items-center ml-3 py-2px btn-bold mr-3">
								<span class="bgc-white-tp9 shadow-sm radius-2px h-4 px-25 pt-1 mr-25 border-1">
									<i class="fa fa-arrow-alt-circle-left text-white-tp2 text-160 " aria-hidden="true"></i>
								</span>
								regresar
							</a>
							<button type="submit" class="btn btn-danger  radius-1 border-b-2 d-inline-flex align-items-center pl-2px py-2px btn-bold">
								<span class="bgc-white-tp9 shadow-sm radius-2px h-4 px-25 pt-1 mr-25 border-1">
									<i class="fa fa-save text-white-tp2 text-160" aria-hidden="true"></i>
								</span>
								guardar
							</button>
						</div>

					</div><!-- /.card-body -->
				</div>
				<div class="border-b-3 w-100 brc-dark radius-b-1"></div>
			</div>
			@*</form>*@
		}
	</div>
</div>
@section PageCrumb{

	<small class="page-info text-secondary-d2">
		<i class="fa fa-angle-double-right text-80" aria-hidden="true"></i>
		Registro de Usuarios
	</small>
}

@section styles{

	<link href="~/assetsAce/node_modules/js/plugins/chosen-js/chosen.css" rel="stylesheet" />

}

@section scripts {
	<script src="~/assetsAce/node_modules/js/plugins/chosen-js/chosen.jquery.js"></script>
	<script src="~/assetsAce/node_modules/js/plugins/inputmask/jquery.inputmask.min.js"></script>
	<script src="~/assetsAce/node_modules/js/plugins/inputmask/inputmask.binding.js"></script>
	@*<script src="~/assetsAce/node_modules/js/plugins/moment/moment.js"></script>*@

	<script type="text/javascript">
		$(function () {
			//aplicamos el pluging a los select´s
			$(".chosen").chosen({
			});
			$('#fileBaucher').aceFileInput({
				style: 'drop',
				droppable: true,
				container: 'border-1 border-dashed brc-grey-l1 brc-h-blue-m2 shadow-sm',
				placeholderClass: 'text-125 text-600 text-grey-l2 my-2',
				placeholderText: 'Drop images here or click to choose',
				placeholderIcon: '<i class="fa fa-cloud-upload-alt fa-3x text-blue-l1 my-2"></i>',
				//previewSize: 80,
				thumbnail: 'large',
				allowExt: 'jpg|jpeg|png',
				//maxSize: 100000,
			})
			$("#ddlPersonasDescontar_chosen").hide();
			$("#divPersonaDescontar").hide();
			$("#divClaveBaucher").hide();
			$("#divComprobanter").hide();
			//$("#divTipoPago").hide();
			LoadFichas();
			ValidatorForm("formExpenses", "Este campo es requerido", "Éxito");
			
		});
		var idSolictante = 0;
		var ubicacion = 0;
		var listConjunto = [];

		$('#TbEmployeeId').change(function (evt) {
			idSolictante = $(this).val();
			FillAval(idSolictante);
			for (var i = 0; i < listConjunto.length; i++) {
				if (listConjunto[i].Ubicacion == "TIERRA" && listConjunto[i].Ficha == ficha) {
					ubicacion = 1;
					
					$("#Location").val(1);
					break;
				} else {
					ubicacion = 2;
					$("#Location").val(2);
					break;
				}

			}
			console.log(ubicacion);
			$(evt.target).valid();
		});
		$('#PaymentType').change(function (evt) {
			var option = $(this).val();
			switch (option) {
				case "1":
					$("#divClaveBaucher").hide();
					$("#divComprobanter").hide();
					$("#divPersonaDescontar").hide();
					$("#ddlPersonasDescontar_chosen").hide();
					$('#AvalName').empty();
					break;
				case "2" :
					$("#divClaveBaucher").show();
					$("#divComprobanter").show();
					$("#divPersonaDescontar").hide();
					$("#ddlPersonasDescontar_chosen").hide();
					$('#AvalName').empty();
					break;
				default:
					$("#divPersonaDescontar").show();
					$("#ddlPersonasDescontar_chosen").show();
					FillAval(idSolictante);
					$("#divClaveBaucher").hide();
					$("#divComprobanter").hide();
			}
			$(evt.target).valid();
		});
		$("#btnCalcular").on("click", function (e) {
			if ($('#TbEmployeeId').val() === "") {
				NotifierMessage(messageSeverity.Info, "Éxito!!", "ñkñklñkñkñ");
				return;
			}
			calculadora();
		});
		function LoadFichas() {
			$.ajax({
				"async": true,
				"url": "@Url.Action("GetEmployeeAval", "Common")",
				type:"json",
				"method": "GET",
			}).done(function (response) {


				$.each(response, function (key, value) {

					listConjunto.push({ Id: value.EmployeeId, Name: value.NameEmployee, Ubicacion: value.WorkLocation });
					//var objCategoria = { Ficha: value.NumberFicha, Situacion: value.ContractualSituation, Ubicacion: value.WorkLocation };
					//listCategoria.push({ Ficha: value.NumberFicha, Situacion: value.ContractualSituation, Ubicacion: value.WorkLocation });

				});

			}).fail(function (jqXHR, textStatus, err) {
				MessageError(jqXHR, textStatus, err, Title, "LnkMessage");
			});
		}

		function FillAval(id) {

			var data = $.grep(listConjunto, function (e) {
				return e.Id != parseInt(id);
			});
			$('#AvalName').empty();
			$.each(data, function (key, value) {
				$('#AvalName')
					.append($("<option></option>")
						.attr("value", value.EmployeeId)
						.text(value.Name));
			});
			$("#AvalName").val('').trigger('chosen:updated');
		}
		function calculadora() {

			var montoCantidad = TransforMoney($('#PaymentAmount').val());


			var pago = 0;
			if (ubicacion == "1") {
				pago = parseFloat(montoCantidad) / 20;
			}
			if (ubicacion == "2") {
				pago = (parseFloat(montoCantidad) / 20) * 2;
			}


			if (!isNaN(pago))
				$("#AbonoCatorcenalMensual").val(pago).formatCurrency();

			pago = 0;
		}
	</script>
}